"""Update UserPastProject to use user_email

Revision ID: 0296a11b83bf
Revises: 94ba2e8ab3f0
Create Date: 2025-11-12 21:02:44.327745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0296a11b83bf'
down_revision: Union[str, Sequence[str], None] = '94ba2e8ab3f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_past_projects', sa.Column('user_email', sa.String(), nullable=False))
    op.drop_constraint(op.f('user_past_projects_user_id_fkey'), 'user_past_projects', type_='foreignkey')
    op.create_foreign_key(None, 'user_past_projects', 'users', ['user_email'], ['email'], ondelete='CASCADE')
    op.drop_column('user_past_projects', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_past_projects', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_past_projects', type_='foreignkey')
    op.create_foreign_key(op.f('user_past_projects_user_id_fkey'), 'user_past_projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_past_projects', 'user_email')
    # ### end Alembic commands ###
