"""add unique constraint to user_skills

Revision ID: 174f1f460c5a
Revises: 2d97e504a3f3
Create Date: 2025-11-14 04:32:23.828037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174f1f460c5a'
down_revision: Union[str, Sequence[str], None] = '2d97e504a3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_skill_user_skill_name', 'user_skills', ['user_id', 'skill_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_skill_user_skill_name', 'user_skills', type_='unique')
    # ### end Alembic commands ###
