"""add unique constraint to user_interests

Revision ID: 2d97e504a3f3
Revises: ba1f791b2c4a
Create Date: 2025-11-14 04:27:06.201944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d97e504a3f3'
down_revision: Union[str, Sequence[str], None] = 'ba1f791b2c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_interest_user_interest_name', 'user_interests', ['user_id', 'interest_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_interest_user_interest_name', 'user_interests', type_='unique')
    # ### end Alembic commands ###
