"""initial schema

Revision ID: 3937871846a4
Revises: 
Create Date: 2025-11-12 22:16:28.776690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3937871846a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_past_projects', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_past_projects_user_email_fkey'), 'user_past_projects', type_='foreignkey')
    op.create_foreign_key(None, 'user_past_projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_past_projects', 'user_email')
    op.add_column('user_skills', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_skills_user_email_fkey'), 'user_skills', type_='foreignkey')
    op.create_foreign_key(None, 'user_skills', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_skills', 'user_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_skills', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_skills', type_='foreignkey')
    op.create_foreign_key(op.f('user_skills_user_email_fkey'), 'user_skills', 'users', ['user_email'], ['email'], ondelete='CASCADE')
    op.drop_column('user_skills', 'user_id')
    op.add_column('user_past_projects', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_past_projects', type_='foreignkey')
    op.create_foreign_key(op.f('user_past_projects_user_email_fkey'), 'user_past_projects', 'users', ['user_email'], ['email'], ondelete='CASCADE')
    op.drop_column('user_past_projects', 'user_id')
    # ### end Alembic commands ###
