"""Update project and team schema

Revision ID: 631efeefe1de
Revises: 683ff4a5ee9d
Create Date: 2025-11-14 00:01:42.332736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631efeefe1de'
down_revision: Union[str, Sequence[str], None] = '683ff4a5ee9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('projects', 'progress',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('teams', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teams', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('teams', 'project_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('project_title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'project_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'progress',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###
