"""Update project schema

Revision ID: 683ff4a5ee9d
Revises: ffea82ccdf23
Create Date: 2025-11-13 23:43:41.517672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683ff4a5ee9d'
down_revision: Union[str, Sequence[str], None] = 'ffea82ccdf23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('last_commit_message', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('last_commit_sha', sa.String(length=64), nullable=True))
    op.add_column('projects', sa.Column('last_commit_url', sa.String(length=500), nullable=True))
    op.alter_column('projects', 'progress',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('projects_owner_id_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('projects_owner_id_fkey'), 'projects', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.alter_column('projects', 'progress',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('projects', 'last_commit_url')
    op.drop_column('projects', 'last_commit_sha')
    op.drop_column('projects', 'last_commit_message')
    # ### end Alembic commands ###
