"""make progress nullable

Revision ID: 767153dffa99
Revises: 62e713363251
Create Date: 2025-11-14 00:28:44.777022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767153dffa99'
down_revision: Union[str, Sequence[str], None] = '62e713363251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'progress',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'progress',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
