"""update progress to accept requirements

Revision ID: 8442f38a32a3
Revises: 767153dffa99
Create Date: 2025-11-14 01:37:23.245370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8442f38a32a3'
down_revision: Union[str, Sequence[str], None] = '767153dffa99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_skill_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=150), nullable=False),
    sa.Column('min_proficiency_level', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_skill_requirements_id'), 'project_skill_requirements', ['id'], unique=False)
    op.add_column('projects', sa.Column('requirements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'requirements')
    op.drop_index(op.f('ix_project_skill_requirements_id'), table_name='project_skill_requirements')
    op.drop_table('project_skill_requirements')
    # ### end Alembic commands ###
