"""Add status to TeamMember

Revision ID: 8525183ff1a5
Revises: 8442f38a32a3
Create Date: 2025-11-14 01:52:24.980256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8525183ff1a5'
down_revision: Union[str, Sequence[str], None] = '8442f38a32a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'status')
    # ### end Alembic commands ###
